name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for version comparison

    - name: Extract Docker version
      id: docker_version
      run: |
        VERSION=$(grep -oP '(?<=^ARG DOCKER_VERSION=)[0-9]+\.[0-9]+\.[0-9]+' docker/Dockerfile)
        echo "DOCKER_VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Verify Dockerfile version update on PR
      if: github.event_name == 'pull_request'
      run: |
        git fetch origin main:main
        if git diff --name-only main..HEAD | grep -q "docker/Dockerfile"; then
          OLD_VERSION=$(git show main:docker/Dockerfile | grep -oP '(?<=^ARG DOCKER_VERSION=)[0-9]+\.[0-9]+\.[0-9]+')
          echo "Old Docker version: $OLD_VERSION"
          if [ "${{ steps.docker_version.outputs.DOCKER_VERSION }}" = "$OLD_VERSION" ]; then
            echo "Error: The Dockerfile was modified, but the DOCKER_VERSION was not updated."
            exit 1
          fi
        fi
        exit 0

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and cache Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dockerfile
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: ghcr.io/${{ github.repository }}:${{ steps.docker_version.outputs.DOCKER_VERSION }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ steps.docker_version.outputs.DOCKER_VERSION }}
        cache-to: type=inline

    - name: Create cache directories
      run: |
        mkdir -p models
        mkdir -p vcpkg_cache

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: vcpkg_cache
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Run build script
      run: ./runDocker.sh --ci ./build.sh
      env:
        VCPKG_CACHE_PATH: ${{ github.workspace }}/vcpkg_cache