name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for version comparison

    - name: Extract Docker version
      id: docker_version
      run: |
        VERSION=$(grep -oP '(?<=^ARG DOCKER_VERSION=)[0-9]+\.[0-9]+\.[0-9]+' docker/Dockerfile)
        echo "DOCKER_VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Verify Dockerfile version update on PR
      if: github.event_name == 'pull_request'
      run: |
        git fetch origin main:main
        # Check if Dockerfile was changed compared to main
        if git diff --name-only main..HEAD | grep -q "docker/Dockerfile"; then
          # Get old version from main, allow failure if file/version doesn't exist
          OLD_VERSION=$(git show main:docker/Dockerfile 2>/dev/null | grep -oP '(?<=^ARG DOCKER_VERSION=)[0-9]+\.[0-9]+\.[0-9]+' || true)
          
          # If an old version exists and it's the same as the new one, fail the build.
          if [ -n "$OLD_VERSION" ] && [ "$OLD_VERSION" = "${{ steps.docker_version.outputs.DOCKER_VERSION }}" ]; then
            echo "Error: The Dockerfile was modified, but the DOCKER_VERSION was not updated."
            echo "Old version: $OLD_VERSION"
            echo "New version: ${{ steps.docker_version.outputs.DOCKER_VERSION }}"
            exit 1
          fi
        fi

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=${{ steps.docker_version.outputs.DOCKER_VERSION }}

    - name: Build and cache Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dockerfile
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
        cache-to: type=inline

    - name: Create cache directories
      run: |
        mkdir -p models
        mkdir -p vcpkg_cache

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: vcpkg_cache
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Run build script
      run: ./runDocker.sh --ci ./build.sh
      env:
        VCPKG_CACHE_PATH: ${{ github.workspace }}/vcpkg_cache